import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/app_theme.dart';

class ServicesScreen extends StatelessWidget {
  const ServicesScreen({Key? key}) : super(key: key);

    static const List<Map<String, dynamic>> _tarifs = [
        {'type': 'Studio', 'surface': '15–30 m²', 'prix': 60, 'icon': Icons.single_bed},
            {'type': 'T2', 'surface': '30–50 m²', 'prix': 75, 'icon': Icons.bed},
                {'type': 'T3', 'surface': '50–70 m²', 'prix': 100, 'icon': Icons.king_bed},
                    {'type': 'Maison', 'surface': '70–120 m²', 'prix': 140, 'icon': Icons.home},
                      ];

                        @override
                          Widget build(BuildContext context) {
                              return Scaffold(
                                    appBar: AppBar(title: Text("Nos Tarifs", style: GoogleFonts.playfairDisplay())),
                                          body: SingleChildScrollView(
                                                  padding: const EdgeInsets.all(20),
                                                          child: Column(
                                                                    crossAxisAlignment: CrossAxisAlignment.start,
                                                                              children: [
                                                                                          const Text("Prestations de base", style: TextStyle(color: JkdColors.gold, fontWeight: FontWeight.bold, fontSize: 16)),
                                                                                                      const SizedBox(height: 12),
                                                                                                                  ..._tarifs.map((t) => Container(
                                                                                                                                margin: const EdgeInsets.only(bottom: 10),
                                                                                                                                              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                                                                                                                                                            decoration: BoxDecoration(color: JkdColors.grey, borderRadius: BorderRadius.circular(10)),
                                                                                                                                                                          child: Row(children: [
                                                                                                                                                                                          Icon(t['icon'] as IconData, color: JkdColors.gold, size: 28),
                                                                                                                                                                                                          const SizedBox(width: 14),
                                                                                                                                                                                                                          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                                                                                                                                                                                                                                            Text(t['type'] as String, style: const TextStyle(fontWeight: FontWeight.bold, color: JkdColors.offWhite)),
                                                                                                                                                                                                                                                              Text(t['surface'] as String, style: const TextStyle(color: Colors.white54, fontSize: 12)),
                                                                                                                                                                                                                                                                              ])),
                                                                                                                                                                                                                                                                                              Text("${t['prix']} €", style: const TextStyle(color: JkdColors.gold, fontWeight: FontWeight.bold, fontSize: 20)),
                                                                                                                                                                                                                                                                                                            ]),
                                                                                                                                                                                                                                                                                                                        )),
                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                const Text("Options (+15€)", style: TextStyle(color: JkdColors.gold, fontWeight: FontWeight.bold, fontSize: 16)),
                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                        ...["Vitres", "Cuisine (Four/Frigo)", "Désinfection"].map((o) => Padding(
                                                                                                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.symmetric(vertical: 6),
                                                                                                                                                                                                                                                                                                                                                                                                    child: Row(children: [
                                                                                                                                                                                                                                                                                                                                                                                                                    const Icon(Icons.add_circle_outline, color: JkdColors.gold, size: 18),
                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(width: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Expanded(child: Text(o, style: const TextStyle(color: JkdColors.offWhite))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const Text("+15 €", style: TextStyle(color: JkdColors.gold, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }